server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  
spring:
  cloud:
    gateway:
      routes:
      - id: product
        uri: http://localhost:8081
        predicates:
        - Path=/prodcut/**
        filters:
        - RewritePath=/product/(?<path>.*), /$\{path}
      - id: review
        uri: lb://review
        predicates:
        - Path=/review/**
        filters:
        - RewritePath=/review/(?<path>.*), /$\{path}
        
management:
  endpoints:
    web:
      exposure:
        include: gateway
