server:
  port: 0
  
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:23306/review?serverTimezone=UTC
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${DISCOVERY_SERVER:localhost:8761}/eureka
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
